const languagePack = {
    ru:{
        title:"Поиск Предков",
        description:"Поиск исторических записей среди многих баз данных",
        lastname:"Фамилия",
        firstname:"Имя",
        middlename:"Отчество",
        birthyear:"Год роджения",
        search:"Поиск",
        resulttext:"Смотреть результаты поиска на",
        lastnameinput:"Иванов",
        firstnameinput:"Иван",
        middlenameinput:"Иванович",
        birthyearinput:"1900",
        error:'Ошибка',
        errordesc:'Заполните поле с фамилией!',
        errorbtn:'Ок',
    },
    ua:{
        title:"Пошук Предків",
        description:"Пошук історичних записів серед багатьох баз даних",
        lastname:"Прізвище",
        firstname:"Ім'я",
        middlename:"По-батькові",
        birthyear:"Рік народження",
        search:"Пошук",
        resulttext:"Переглянути результати пошуку на",
        lastnameinput:"Іванов",
        firstnameinput:"Іван",
        middlenameinput:"Іванович",
        birthyearinput:"1900",
        error:'Помилка',
        errordesc:'Заповніть поле з прізвищем!',
        errorbtn:'Ок',
    },
    en:{
        title:"Ancestor Search Portal",
        description:"Search for historical records across multiple databases",
        lastname:"Last Name",
        firstname:"First Name",
        middlename:"Middle Name",
        birthyear:"Birth Year",
        search:"Search",
        resulttext:"View Results on",
        lastnameinput:"Ivanov",
        firstnameinput:"Ivan",
        middlenameinput:"Ivanovich",
        birthyearinput:"1900",
        error:'Error',
        errordesc:'Fill in the surname field!',
        errorbtn:'Ok',
    },
    be: { // Belarusian
        title:"Пошук Продкаў",
        description:"Пошук гістарычных запісаў сярод многіх баз дадзеных",
        lastname:"Прозвішча",
        firstname:"Імя",
        middlename:"Імя па бацьку",
        birthyear:"Год нараджэння",
        search:"Пошук",
        resulttext:"Глядзець вынікі пошуку на",
        lastnameinput:"Іваноў",
        firstnameinput:"Іван",
        middlenameinput:"Іванавіч",
        birthyearinput:"1900",
        error:'Памылка',
        errordesc:'Запоўніце поле прозвішча!',
        errorbtn:'Добра',
    },
    kk: { // Kazakh
        title:"Ата-тегін іздеу",
        description:"Түрлі деректер қорларынан тарихи жазбаларды іздеу",
        lastname:"Тегі",
        firstname:"Аты",
        middlename:"Әкесінің аты",
        birthyear:"Туған жылы",
        search:"Іздеу",
        resulttext:"Іздеу нәтижелерін қарау",
        lastnameinput:"Иванов",
        firstnameinput:"Иван",
        middlenameinput:"Иванұлы",
        birthyearinput:"1900",
        error:'Қате',
        errordesc:'Тегі өрісін толтырыңыз!',
        errorbtn:'Жақсы',
    },
    pl: { // Polish
        title:"Portal Poszukiwań Przodków",
        description:"Wyszukiwanie historycznych записей w wielu bazach danych",
        lastname:"Nazwisko",
        firstname:"Imię",
        middlename:"Drugie imię",
        birthyear:"Rok urodzenia",
        search:"Szukaj",
        resulttext:"Wyświetl wyniki wyszukiwania na",
        lastnameinput:"Iwanow",
        firstnameinput:"Iwan",
        middlenameinput:"Iwanowicz",
        birthyearinput:"1900",
        error:'Błąd',
        errordesc:'Wypełnij pole nazwiska!',
        errorbtn:'Ok',
    },
    bg: { // Bulgarian
        title:"Портал за Търсене на Предци",
        description:"Търсене на исторически записи сред множество бази данни",
        lastname:"Фамилия",
        firstname:"Име",
        middlename:"Презиме",
        birthyear:"Година на раждане",
        search:"Търсене",
        resulttext:"Преглед на резултатите от търсенето на",
        lastnameinput:"Иванов",
        firstnameinput:"Иван",
        middlenameinput:"Иванович",
        birthyearinput:"1900",
        error:'Грешка',
        errordesc:'Попълнете полето за фамилия!',
        errorbtn:'Добре',
    },
    ro: { // Romanian
        title:"Portal de Căutare a Strămoșilor",
        description:"Căutare înregistrări istorice în mai multe baze de date",
        lastname:"Nume",
        firstname:"Prenume",
        middlename:"Numele mijlociu",
        birthyear:"An de naștere",
        search:"Caută",
        resulttext:"Vizualizează rezultatele căutării pe",
        lastnameinput:"Ivanov",
        firstnameinput:"Ivan",
        middlenameinput:"Ivanovici",
        birthyearinput:"1900",
        error:'Eroare',
        errordesc:'Completați câmpul pentru nume!',
        errorbtn:'Ok',
    },
}

const portals2 = [
    {
        title:{
            ru:'FamilySearch (c 1700)',
            ua:'FamilySearch (з 1700)',
            en:'FamilySearch (since 1700)',
            be:'FamilySearch (з 1700)',
            kk:'FamilySearch (1700 жылдан бастап)',
            pl:'FamilySearch (od 1700)',
            bg:'FamilySearch (от 1700)',
            ro:'FamilySearch (din 1700)',
        },
        id:1,
    },
    {
        title:{
            ru:'Первая Мировая Война',
            ua:'Перша Світова Війна',
            en:'World War 1',
            be:'Першая Сусветная Вайна',
            kk:'Бірінші Дүниежүзілік Соғыс',
            pl:'Pierwsza Wojna Światowa',
            bg:'Първата Световна Война',
            ro:'Primul Război Mondial',
        },
        id:2,
    },
    {
        title:{
            ru:'Вторая Мировая Война',
            ua:'Друга Світова Війна',
            en:'World War 2',
            be:'Другая Сусветная Вайна',
            kk:'Екінші Дүниежүзілік Соғыс',
            pl:'Druga Wojna Światowa',
            bg:'Втората Световна Война',
            ro:'Al Doilea Război Mondial',
        },
        id:3,
    },
    {
        title:{
            ru:'Вторая Мировая Война',
            ua:'Друга Світова Війна',
            en:'World War 2',
            be:'Другая Сусветная Вайна',
            kk:'Екінші Дүниежүзілік Соғыс',
            pl:'Druga Wojna Światowa',
            bg:'Втората Световна Война',
            ro:'Al Doilea Război Mondial',
        },
        id:4,
    },
    {
        title:{
            ru:'Репрессированные в СССР',
            ua:'Репресовані в СРСР',
            en:'Repressed in USSR',
            be:'Рэпрэсаваныя ў СРСР',
            kk:'КСРО-да қуғынға ұшырағандар',
            pl:'Represjonowani w ZSRR',
            bg:'Репресирани в СССР',
            ro:'Represiați în URSS',
        },
        id:5,
    },
    {
        title:{
            ru:'Репрессированные в Германии',
            ua:'Репресовані в Німеччині',
            en:'Repressed in Germany',
            be:'Рэпрэсаваныя ў Германіі',
            kk:'Германияда қуғынға ұшырағандар',
            pl:'Represjonowani w Niemczech',
            bg:'Репресирани в Германия',
            ro:'Represiați în Germania',
        },
        id:6,
    },
    {
        title:{
            ru:'База Жителей Украины',
            ua:'База Мешканців України',
            en:'Ukrainian Citizens Database',
            be:'База Жыхароў Украіны',
            kk:'Украина Тұрғындарының Базасы',
            pl:'Baza Obywateli Ukrainy',
            bg:'База на Украински Граждани',
            ro:'Baza de Date a Cetățenilor Ucraineni',
        },
        id:7,
    },
    {
        title:{
            ru:'MyHeritage (ограничено)',
            ua:'MyHeritage (обмежено)',
            en:'MyHeritage (limited)',
            be:'MyHeritage (абмежавана)',
            kk:'MyHeritage (шектеулі)',
            pl:'MyHeritage (ograniczone)',
            bg:'MyHeritage (ограничено)',
            ro:'MyHeritage (limitat)',
        },
        id:8,
    },
];